notifications:
  slack:
    secure: JeQppkUR9W0Z4EdN9t6RW4oUM4XXSDgqz1rrPZvoxUGpsJc2RWSQxQ8wnYgZ3yRHR8Vn/0Prb9PyUHCfFbgwJMazlbKtcQEtLoG7nLIGFm3ro08k/EzrHiXXQbYWkAeG1dE9s1qqC0+0gKmvB9MLrR3LMg6VWe+cKs6N9SWyg28NVFCJvAu+5IZ3DhLpRayreTRuEYtiN92Pv84Jg8u4JB01W1hxIx/g/cLtzeoEc2YDGlysFV7CsHdZnzpBMWUcorg1LE6j5wNj4IDTGVd9SXjvwp5FogLNdlB7IRO3ayDUIAuBpt9VhkATGQmqVBSeTefILEwF3ff5EhEs94/hFxvu0tKoykppatATcTzoSjQsfLiArOxB2O/pWMFQamQtx8YDpr4pANyv7XOEzTC2LckKlN/gBhxVSezLnmhyL0eQy52tqm2SeV60XCB43KQmvRqOU40OG86BUiXqxWa7gl9NV2zODErm7Zzh+vOonq+0i8ToXroTcM8Qp63b6iJlMqRN8KnxbvGy5ZdMLMaP0626DWmN/VWyqyweF99WFWoQaM02jY+GfVohZo/2W6MN52J8KMR0rl/FWjUWHvBbm9tEl2+0plTVy6CSOAjz6h9lhxB14gmitlNjEzlLdz0lbdd17YBrwlivZpSslUk+AOwZho4QGLsmb2HUXmdjvCk=

language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

env:
  global:
  - PATH="$PATH:$HOME/.composer/vendor/bin"
  #- secure: MAILTRAP_INBOX_ID
  #- secure: MAILTRAP_TOKEN
  #- secure: MAILTRAP_SMTP_USERNAME
  #- secure: MAILTRAP_SMTP_PASSWORD

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  - git config --global github.accesstoken $GITHUB_OAUTH_TOKEN
  - sudo apt-get update > /dev/null
  - composer self-update

install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

  - composer global require drush/drush:dev-master
  - composer global require --no-interaction "hirak/prestissimo:^0.3"
  - phpenv rehash

  - mysql -e 'create database drupal;'

  - cd ..
  - drush dl drupal-8 --drupal-project-rename=drupal
  - mv netsmtp drupal/modules
  - cd drupal
  - export DRUPAL_DIR=$(pwd)

  # Install drupal default profile
  - drush --verbose site-install --db-url=mysql://root:@127.0.0.1/drupal --yes
  - drush en -y netsmtp

script:
  - cd modules/netsmtp/src/Tests/Integration && php -f runtests.php
