<?php
/**
 * @file
 * Net SMTP module.
 */

define('NETSMTP_SETTINGS', 'netsmtp.settings');

use Drupal\Core\Url;
/**
 * Implements hook_mail().
 */
function netsmtp_mail($key, &$message) {
  switch ($key) {
    case 'test_message':
      $uuid = \Drupal\Component\Uuid\Php::generate();
      $message['subject'] = 'uniq-mailtrap-id:' . $uuid;
      \Drupal::state()->set('netsmtp.last_message_id', $message['subject']);
      $message['body'][] = t('Testing Net Smtp mailer.');
      break;
  }
}




/**
 * Implements hook_mail_alter().
 */
function netsmtp_mail_alter(&$message) {
  $config = \Drupal::config(NETSMTP_SETTINGS);

  if ($config->get('netsmtp_debug_trace')) {
    $path = $config->get('netsmtp_debug_trace_path');
    file_prepare_directory($path, FILE_CREATE_DIRECTORY | FILE_MODIFY_PERMISSIONS);
    $filename = $path . '/netsmtp-trace-' . date('Y-m-d') . '.log';

    $data = array();
    $data[] = 'Sent at ' . date('Y_m_d-H_i_s');
    $data[] = 'Module: ' . $message['module'] . ', key: ' . $message['key'];
    $data[] = 'Recipient: ' . $message['to'];
    $data[] = 'Subject: ' . $message['subject'];
    $data[] = 'Stack trace:';
    ob_start();
    debug_print_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS);
    $data[] = ob_get_clean();
    $data[] = '';

    file_put_contents($filename, implode("\n", $data), FILE_APPEND | LOCK_EX );
  }

  if ($recipient = $config->get('netsmtp_catch')) {

    $front_page_url = Url::fromUri('base:/', ['absolute' => TRUE]);
    $message['headers']['X-Catched-Mail-Key'] = isset($message['id']) ? $message['id'] : null;
    $message['headers']['X-Catched-Website'] = $front_page_url->toString();
    $message['headers']['X-Catched-Original-To'] = $message['to'];
    $message['to'] = is_array($recipient) ? implode(',', $recipient) : $recipient;

    foreach ($message['headers'] as $header => $value) {
      switch (strtolower($header)) {

        case 'cc':
        case 'bcc':
          unset($message['headers'][$header]);
          $message['headers']['X-Rerouted-Original-' . $header] = $value;
          break;
      }
    }
  }
}

