netsmtp.settings:
  type: config_object
  label: 'Netsmtp settings'
  mapping:
    netsmtp_subject_encode:
      type: boolean
      label: 'Encode mail subjects'

    netsmtp_debug_mime:
      type: boolean
      label: 'Sent data dumping'

    netsmtp_debug_mime_path:
      type: string
      label: 'Sent data dumping path'

    netsmtp_debug_trace:
      type: boolean
      label: 'Sent mail trace'

    netsmtp_debug_trace_path:
      type: string
      label: 'Sent mail trace debug path'

    netsmtp_catch:
      type: sequence
      label: 'Re-route emails'
      sequence:
        type: email
        label: 'Re-route email'
    providers:
      type: sequence
      label: List of modules
      sequence:
        type: sequence
        label: List of keys for a given module
        sequence:
          type: mapping
          label: Per module/key setting.
          mapping:
            hostname:
              type: string
              label: 'Hostname'
            port:
              type: string
              label: 'port'
            use_ssl:
              type: string
              label: 'ssl or tls'
              description: 'true/false for "ssl" & tls to use "tls".'
            username:
              type: string
              label: 'Username'
            password:
              type: string
              label: 'Password'
            localhost:
              type: string
              label: 'Localhost'
              description: 'The value to give when sending EHLO or HELO.'

